### ISSUE TITLE
Parking value not exclude // Wrap around not handled

### ISSUE THREAD

**Issue by jzulauf** [krizhanovsky/NatSys-Lab#4]
Please forgive me if I'm missing something here...

in lockfree_rb_q.cc class LockFreeQueue, there appear to be two issues related to ulong overflow (wrap around).  

1) the ULONG_MAX "parking value" is not excluded from reservation, nor from "min" testing.  the "invalid" value can't ever be used as a valid value, nor compared with them

2) the comparison for min testing will be incorrect if the span of thread specific head and tail values crosses overflow

There appear to be two choice -- compared the signed distance, If the max difference is representable in long, will give the correct comparison (if the difference isn't,  then one push of pop isn't making forward progress... or you have more than 2 billion threads)

( 0  < long(min - tmp_[ht})

Slightly more robust (it could handle a ULONG_MAXth old pending request :) ) would be comparing the head - tail values -- guaranteed to be positive and correctly comparable -, though eventually a hung push or pop operation would stall all operations.

**Comment by krizhanovsky** [comment]
Hi!

I use unsigned long, which is 64 bits in size, exactly to avoid overflow issues as well as additional cost on integer overflow management. If we suppose a 3Ghz processor incrementing unsigned long variable each tick, then it'll require almost 195 years to overflow the variable

        $ perl -le 'print +(~1 / 3_000_000_000 / 3600 / 24 / 365)'
        194.980805785024

So we can safely suppose that we're safe from integer overflows.

**Comment by jzulauf** [comment]
for x64, you're certainly correct.  for x86 32, long is 32 bits, at least on compilers with which I've familiar, and people still build and run 32 bit code, At the rate of about 125ns per push or pop operation I measured for boost::lockfree in my testing, would overflow in about 20 minutes.

Probably the simplest fix is to detect 32bit at compile time and typedef the counters to ulonglong... though it would be interesting to bench the overflow management logic versus the additional width.

BTW -- brilliant article, clearest exposition on a lock-free design.

**Comment by krizhanovsky** [comment]
The queue is designed specially for x86_64 and we ever check this at compile time https://github.com/krizhanovsky/NatSys-Lab/blob/master/lockfree_rb_q.cc#L25 .

And thanks for good words ;)
